# Generated by Django 5.0.1 on 2024-01-18 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
